### ISSUE TITLE
how to run it ?

### ISSUE THREAD

**Issue by catafest** [pbatard/fasmg-ebc#3]
How to run it with qemu under Windows OS?

**Comment by pbatard** [comment]
Open a command prompt in the directory where you cloned fasmg-ebc and run `make qemu` as indicated by the readme. This will call the `make.cmd` batch file. Don't let the mention of `make` fool you into thinking that this is a UNIX thing.

If that doesn't work, edit the variables from `make.cmd` accordingly.

EDIT: Corrected `make` &rarr; `make qemu`

**Comment by catafest** [comment]
I take a look at make.cmd , anyway not working ... 
```
C:\>cd fasmg-ebc-master

C:\fasmg-ebc-master>make.cmd
fasmg hello.asm hello.efi
flat assembler  version g.hsjj0
3 passes, 0.2 seconds, 1536 bytes.

C:\fasmg-ebc-master>make
fasmg hello.asm hello.efi
flat assembler  version g.hsjj0
3 passes, 1536 bytes.

C:\fasmg-ebc-master>make qemu
fasmg hello.asm hello.efi
flat assembler  version g.hsjj0
3 passes, 0.1 seconds, 1536 bytes.

The UEFI firmware file, needed for QEMU, is being downloaded from:
http://efi.akeo.ie/OVMF/OVMF-X64.zip
Note: Unless you delete the file, this should only happen once.

qemu-system-x86_64w.exe -net none -monitor none -parallel none -L . -bios OVMF_X64.fd -hda fat:image
C:\fasmg-ebc-master>make.cmd
fasmg hello.asm hello.efi
flat assembler  version g.hsjj0
3 passes, 1536 bytes.

C:\fasmg-ebc-master>make
fasmg hello.asm hello.efi
flat assembler  version g.hsjj0
3 passes, 1536 bytes.
```

**Comment by pbatard** [comment]
Do you have QEMU installed in `C:\Program Files\qemu\` ?

You need to install QEMU, as make.cmd will not to that for you! And it must be in `C:\Program Files\qemu\` (or you need to edit the variables in `make.cmd`). Please look at the __Prerequisites__ from the README.

**Comment by catafest** [comment]
I have qemu the result is nothing ...
```
C:\>cd fasmg-ebc-master

C:\fasmg-ebc-master>make.cmd
fasmg hello.asm hello.efi
flat assembler  version g.hsjj0
3 passes, 0.2 seconds, 1536 bytes.

C:\fasmg-ebc-master>make
fasmg hello.asm hello.efi
flat assembler  version g.hsjj0
3 passes, 1536 bytes.

C:\fasmg-ebc-master>make qemu
fasmg hello.asm hello.efi
flat assembler  version g.hsjj0
3 passes, 0.1 seconds, 1536 bytes.

The UEFI firmware file, needed for QEMU, is being downloaded from:
http://efi.akeo.ie/OVMF/OVMF-X64.zip
Note: Unless you delete the file, this should only happen once.

qemu-system-x86_64w.exe -net none -monitor none -parallel none -L . -bios OVMF_X64.fd -hda fat:image
```
`

**Comment by catafest** [comment]
Yes I have it on that path C:\Program Files\qemu\
version qemu-w64-setup-20170420.exe

**Comment by pbatard** [comment]
Try `make hello qemu`

**Comment by pbatard** [comment]
Also, please make sure you can run `qemu-system-x86_64w.exe` with regular UEFI applications __BEFORE__ you test with EBC. I'm afraid I don't want to have to help you figure out how you should configure QEMU (or whether the latest build of QEMU for Windows is broken, as has happened before), as I fully expect people using `fasmg-ebc` to have that sorted out already. If you need help, please see the QEMU forums.

**Comment by catafest** [comment]
nothing 
```
C:\fasmg-ebc-master>make hello qemu
fasmg hello.asm hello.efi
flat assembler  version g.hsjj0
3 passes, 0.1 seconds, 1536 bytes.

qemu-system-x86_64w.exe -net none -monitor none -parallel none -L . -bios OVMF_X64.fd -hda fat:image
C:\fasmg-ebc-master>
```

how can I be sure I run qemu-system-x86_64w.exe with regular UEFI applications.
Is first test .

**Comment by pbatard** [comment]
> how can I be sure I run qemu-system-x86_64w.exe with regular UEFI applications.

It's up to you to become familiar enough with qemu and OVMF. `fasmg-ebc` is __NOT__ and entry-level application into UEFI. Instead, I expect `fasmg-ebc` users to already be familiar with the tools and frameworks being used in relation to UEFI (since EBC is really an advanced UEFI concept).

So if you need help with that, then I will kindly ask that you look for that help elsewhere, as I don't have the resources to hold hands to people who aren't already familiar with `qemu` and `OVMF` usage. You should be able to google around to find the tutorials you need on that.

The one thing that I will do however (when I get a chance), is see if there an issue with `qemu-w64-setup-20170420.exe`, as I have found that the Windows build of `qemu` can sometime be a bit unstable. You may also try to install `qemu-w64-setup-20160903.exe` (which, _I believe_, is the version I installed), and see if that works better.

**Comment by pbatard** [comment]
Welp, the latest QEMU Win32 binary is broken (be mindful that the page explicitly states: _"QEMU for Windows is experimental software and might contain even serious bugs, so use the binaries at your own risk."_). Use `qemu-w64-setup-20170131.exe` and you should be good.

**Comment by pbatard** [comment]
I'm going to consider this issue closed.
