### ISSUE TITLE
Comparison Instruction Allows Indirect Op1

### ISSUE THREAD

**Issue by Pebaz** [pbatard/fasmg-ebc#4]
I have been absolutely amazed on how high quality your project is! 😃

Seriously, you literally created an assembler on top of FASMG, that's insanely cool!

Something that could be improved is that the `CMP64eq` instruction allows operand 1 to be indirect when section 22.8 (CMP) states that operand 1 can only be direct. Now, I could be 100% wrong but when I stopped using this syntax `CMP64eq @R1, @R2` it worked fine.

Essentially:

```
;; This shouldn't be able to work:
CMP64eq @R1, @R2

;; Should be this instead:
MOVq R1, @R1
MOVq R2, @R2
CMP64eq R1, R2

;; Or slightly shorter
MOVq R1, @R1
CMP64eq R1, @R2
```

**Comment by pbatard** [comment]
Thanks for reporting this.

At this stage, I'm not sure if I'll ever go back to the EBC assembler, as I was hoping it might lead to something useful for some of my other projects when I was developing this one, but I have since moved away from that view.

**Comment by Pebaz** [comment]
@pbatard Thank you for the update, I completely understand! :)
